- name: setup argocd
  block:
    - name: clone repo argocd-appsets
      git:
        repo: https://github.com/vit0r/argocd-appsets.git
        dest: /src/argocd-appsets
        single_branch: yes
        force: yes
        version: main
    - name: create
      shell: ls *.yaml
      args:
        chdir: /src/argocd-appsets
    - name: download argocd
      vars:
        argocd_version: v2.14.9
      get_url:
        url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-linux-amd64"
        dest: /usr/local/bin/argocd
        owner: root
        mode: 0770
